# Generated by Django 5.0.1 on 2024-03-27 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0010_alter_actions_tags_managers_action_unprocessed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=None, null=True)),
                ("end_time", models.DateTimeField(default=None, null=True)),
                ("duration", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="completed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stuff_manager.actioncompletion",
            ),
        ),
    ]
