# Generated by Django 5.0.1 on 2024-03-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stuff_manager",
            "0014_completion_notes_remove_action_completion_notes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="completion_notes",
            name="duration",
            field=models.TimeField(default=None, null=True),
        ),
    ]
