# Generated by Django 5.0.1 on 2024-03-28 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stuff_manager",
            "0014_remove_action_completion_notes_completion_notes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="completion_notes",
            name="action",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completion_notes",
                to="stuff_manager.action",
            ),
        ),
    ]
