# Generated by Django 5.0.1 on 2024-03-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0015_remove_completion_notes_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="completion_notes",
            name="duration",
            field=models.TimeField(default=None, null=True),
        ),
    ]
