# Generated by Django 5.0.1 on 2024-03-29 22:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0016_completion_notes_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completion_notes",
            name="duration",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(default=0),
                null=True,
                size=None,
            ),
        ),
    ]
