# Generated by Django 4.2.7 on 2023-11-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0003_user_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clerkId",
            field=models.CharField(blank=True, default="", max_length=256, null=True),
        ),
    ]
