# Generated by Django 4.2.7 on 2023-11-16 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0004_user_clerkid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="clerkId",
            new_name="clerk_id",
        ),
    ]
