# Generated by Django 4.2.7 on 2023-11-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0005_rename_clerkid_user_clerk_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="clerk_id",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
