# Generated by Django 4.2.7 on 2023-12-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0008_unprocessed"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="energy",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
