# Generated by Django 5.0.1 on 2024-03-27 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0011_actioncompletion_action_completed_action_completion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="completion",
            new_name="completion_notes",
        ),
    ]
