# Generated by Django 5.0.1 on 2024-03-27 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0012_rename_completion_action_completion_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="completion_notes",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stuff_manager.actioncompletion",
            ),
        ),
    ]
