# Generated by Django 5.0.1 on 2024-03-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0013_alter_action_completion_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Completion_Notes",
            fields=[
                (
                    "action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="completion_notes",
                        serialize=False,
                        to="stuff_manager.action",
                    ),
                ),
                ("start_time", models.DateTimeField(default=None, null=True)),
                ("end_time", models.DateTimeField(default=None, null=True)),
                ("duration", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="action",
            name="completion_notes",
        ),
        migrations.DeleteModel(
            name="ActionCompletion",
        ),
    ]
