# Generated by Django 5.0.1 on 2024-03-28 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "stuff_manager",
            "0014_completion_notes_remove_action_completion_notes_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completion_notes",
            name="duration",
        ),
    ]
