# Generated by Django 5.0.1 on 2024-04-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0016_completion_notes_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="completed",
        ),
        migrations.AddField(
            model_name="action",
            name="completed_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="deleted_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
