# Generated by Django 5.0.1 on 2024-04-19 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stuff_manager",
            "0017_remove_action_completed_action_completed_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="unprocessed",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
