# Generated by Django 5.0.1 on 2024-04-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0019_action_stuff_manag_created_fcc5a6_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="unprocessed",
            index=models.Index(
                fields=["created"], name="stuff_manag_created_7d7669_idx"
            ),
        ),
    ]
