# Generated by Django 5.0.1 on 2024-04-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuff_manager", "0020_unprocessed_stuff_manag_created_7d7669_idx"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Actions_RequiredContexts",
            new_name="Actions_Contexts",
        ),
        migrations.RemoveIndex(
            model_name="action",
            name="stuff_manag_created_6e8dac_idx",
        ),
        migrations.RemoveIndex(
            model_name="action",
            name="stuff_manag_title_a53497_idx",
        ),
        migrations.RenameField(
            model_name="action",
            old_name="title",
            new_name="name",
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["created", "name"], name="stuff_manag_created_a667da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["name"], name="stuff_manag_name_1af169_idx"),
        ),
    ]
